Время ошибки,Тип и место ошибки
2023-06-21 10:20:24,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/1468023064.py"", line 254, in <module>
    df.to_csv(r'C:\Users\agd01\таблицы со сделками бота\scalping_bot_12_2_2\scalping_bot_version12_2_2_2.csv',
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\core\generic.py"", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\format.py"", line 1105, in to_csv
    csv_formatter.save()
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\csvs.py"", line 237, in save
    with get_handle(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\common.py"", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\agd01\\таблицы со сделками бота\\scalping_bot_12_2_2\\scalping_bot_version12_2_2_2.csv'
"
2023-06-21 09:57:53,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/1468023064.py"", line 254, in <module>
    df.to_csv(r'C:\Users\agd01\таблицы со сделками бота\scalping_bot_12_2_2\scalping_bot_version12_2_2_2.csv',
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\core\generic.py"", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\format.py"", line 1105, in to_csv
    csv_formatter.save()
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\csvs.py"", line 237, in save
    with get_handle(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\common.py"", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\agd01\\таблицы со сделками бота\\scalping_bot_12_2_2\\scalping_bot_version12_2_2_2.csv'
"
2023-06-21 09:57:49,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/1468023064.py"", line 254, in <module>
    df.to_csv(r'C:\Users\agd01\таблицы со сделками бота\scalping_bot_12_2_2\scalping_bot_version12_2_2_2.csv',
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\core\generic.py"", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\format.py"", line 1105, in to_csv
    csv_formatter.save()
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\csvs.py"", line 237, in save
    with get_handle(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\common.py"", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\agd01\\таблицы со сделками бота\\scalping_bot_12_2_2\\scalping_bot_version12_2_2_2.csv'
"
2023-06-21 04:11:30,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/1468023064.py"", line 161, in <module>
    if float(find_list(format(nearest_max, f'.{price_precision}f'), glass['bids'])[1][1]) >= np.mean(
TypeError: 'NoneType' object is not subscriptable
"
2023-06-21 04:03:57,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/1468023064.py"", line 161, in <module>
    if float(find_list(format(nearest_max, f'.{price_precision}f'), glass['bids'])[1][1]) >= np.mean(
TypeError: 'NoneType' object is not subscriptable
"
2023-06-20 16:47:57,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/2084043156.py"", line 161, in <module>
    if float(find_list(format(nearest_max, f'.{price_precision}f'), glass['bids'])[1][1]) >= np.mean(
TypeError: 'NoneType' object is not subscriptable
"
2023-06-20 12:32:36,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/2084043156.py"", line 254, in <module>
    df.to_csv(r'C:\Users\agd01\таблицы со сделками бота\scalping_bot_12_2_2\scalping_bot_version12_2_2_2.csv',
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\core\generic.py"", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\format.py"", line 1105, in to_csv
    csv_formatter.save()
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\csvs.py"", line 237, in save
    with get_handle(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\common.py"", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\agd01\\таблицы со сделками бота\\scalping_bot_12_2_2\\scalping_bot_version12_2_2_2.csv'
"
2023-06-20 12:32:33,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/2084043156.py"", line 254, in <module>
    df.to_csv(r'C:\Users\agd01\таблицы со сделками бота\scalping_bot_12_2_2\scalping_bot_version12_2_2_2.csv',
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\core\generic.py"", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\format.py"", line 1105, in to_csv
    csv_formatter.save()
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\csvs.py"", line 237, in save
    with get_handle(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\common.py"", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\agd01\\таблицы со сделками бота\\scalping_bot_12_2_2\\scalping_bot_version12_2_2_2.csv'
"
2023-06-20 12:32:29,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/2084043156.py"", line 254, in <module>
    df.to_csv(r'C:\Users\agd01\таблицы со сделками бота\scalping_bot_12_2_2\scalping_bot_version12_2_2_2.csv',
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\core\generic.py"", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\format.py"", line 1105, in to_csv
    csv_formatter.save()
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\csvs.py"", line 237, in save
    with get_handle(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\common.py"", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\agd01\\таблицы со сделками бота\\scalping_bot_12_2_2\\scalping_bot_version12_2_2_2.csv'
"
2023-06-19 21:53:01,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/2084043156.py"", line 161, in <module>
    if float(find_list(format(nearest_max, f'.{price_precision}f'), glass['bids'])[1][1]) >= np.mean(
TypeError: 'NoneType' object is not subscriptable
"
2023-06-19 21:52:29,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/2084043156.py"", line 141, in <module>
    if float(find_list(format(nearest_min, f'.{price_precision}f'), glass['asks'])[1][1]) >= np.mean(
TypeError: 'NoneType' object is not subscriptable
"
2023-06-19 11:57:00,"Traceback (most recent call last):
  File ""C:\Users\agd01\AppData\Local\Temp/ipykernel_11048/2084043156.py"", line 254, in <module>
    df.to_csv(r'C:\Users\agd01\таблицы со сделками бота\scalping_bot_12_2_2\scalping_bot_version12_2_2_2.csv',
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\core\generic.py"", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\format.py"", line 1105, in to_csv
    csv_formatter.save()
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\formats\csvs.py"", line 237, in save
    with get_handle(
  File ""C:\Users\agd01\anaconda3\lib\site-packages\pandas\io\common.py"", line 702, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\agd01\\таблицы со сделками бота\\scalping_bot_12_2_2\\scalping_bot_version12_2_2_2.csv'
"
